language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

matrix:
  allow_failures:
    - php: 7.3

env:
  - SYMFONY_VERSION=2.8.*

before_install:
  - phpenv config-add travis/z_php.ini

before_script:
  - composer install --prefer-dist --no-interaction

script:
  - SYMFONY_PHPUNIT_VERSION=6.5 SYMFONY_DEPRECATIONS_HELPER=weak bin/simple-phpunit --coverage-text

notifications:
  email:
    recipients:
      - si-integration@smartandco.com
    on_success: change
    on_failure: always

